### ISSUE TITLE
Not able to view the screenshots in the html report

### ISSUE THREAD

**Issue by kaustavbasu075** [abhishekkyd/protractor-html-reporter-2#6]
Hi Guys,

I am not able to see the the screenshot in the html file.It displays an error screenshot not found.I even checked out your example ,ProtractorTestReport and it displays the same error.
Please let me know if i am missing anything or need to do anything differently.

**Comment by abhishekkyd** [comment]
@kaustavbasu075 please attach the screenshot of your report with highlighting the screenshot URL.

**Comment by kaustavbasu075** [comment]
Hi @abhishekkyd ,Please find the screenshot below
![htmlreportscreenshot](https://user-images.githubusercontent.com/25998309/38793150-5722fc98-4193-11e8-98fb-6ef3e1085a46.PNG)

**Comment by jamesomorodion** [comment]
@kaustavbasu075 is this still a blocker/issue for you?

**Comment by mdmoeenajazkhan** [comment]
@abhishekkyd  and @jamesomorodion I'm facing same issue. In screenshot folder there is no png file.
In html file when you click on the link, it keeps loading

**Comment by telangn** [comment]
This is an issue for me as well. I am giving the right path. But I too am getting Screenshot Not Found

**Comment by nikhilgupta1789** [comment]
Actually the issue is when you have long sentence in it block then it finds difficulty in finding long path of screenshot, because screenshot name saved in name of it block sentence. Are there any way to save the screenshot name instead of it block name and map it with html reporter? @abhishekkyd  @jamesomorodion

**Comment by lukzeg** [comment]
Hi @jamesomorodion , @abhishekkyd 
I noticed the same problem as other people. I looked inside your code and I noticed that inside code the *href* and *src* attribute does not encode spaces. After encoding them, everything started to work for me.

I noticed as well second problem.
The screenshot names aren't the same as names created in the reporter if we use this logic:
describe('testSuite', function() {
  describe('testSuiteDeeperName', function() {
     it('test1', function() {})
        expect(2).toBe(1)
  })
})

The reporter will expect to find:
'''
testSuite.testSuiteDeeperName test1.png
'''
screenshot, but inside screenshot folder we will find:
'''
testSuite testSuiteDeeperName test1.png
'''
The proposal with fix for both of the issues you can find in PR: https://github.com/abhishekkyd/protractor-html-reporter-2/pull/12.
Please let me know if it suits you, or I should fix something.

**Comment by kmanikandanmca2008** [comment]
@kaustavbasu075  This issue is fixed now and it is working fine.
Your problem root cause may be the screenshotPath property value do not change  so it should be'  screenshotPath: './screenshots'.

**Comment by singhrajkr** [comment]
@abhishekkyd @jamesomorodion @kmanikandanmca2008 
I am also facing same issue even keeping the same exact path for `'screenshotPath: './screenshots'.` 

Why, This issue is still open even it has been reported 2 years back.

**Comment by MinhalAbbas000** [comment]
I am also facing this issue.

**Comment by JyothishreeR** [comment]
> Hi @jamesomorodion , @abhishekkyd
> I noticed the same problem as other people. I looked inside your code and I noticed that inside code the _href_ and _src_ attribute does not encode spaces. After encoding them, everything started to work for me.
> 
> I noticed as well second problem.
> The screenshot names aren't the same as names created in the reporter if we use this logic:
> describe('testSuite', function() {
> describe('testSuiteDeeperName', function() {
> it('test1', function() {})
> expect(2).toBe(1)
> })
> })
> 
> The reporter will expect to find:
> '''
> testSuite.testSuiteDeeperName test1.png
> '''
> screenshot, but inside screenshot folder we will find:
> '''
> testSuite testSuiteDeeperName test1.png
> '''
> The proposal with fix for both of the issues you can find in PR: #12.
> Please let me know if it suits you, or I should fix something.

I am still facing this issue.. 
In the html report - the error is reported and it shows an icon in place of screenshot.. I am expecting screenshot to be loaded here...
(The screenshot is seen in screenshot/images folder )

**Comment by JyothishreeR** [comment]
I am still facing this issue..
In the html report - the error is reported and it shows an icon in place of screenshot.. I am expecting screenshot to be loaded here...
(The screenshot is seen in screenshot/images folder )
